import os
dst = r'C:\Colgram\Telegram-Src\TMessagesProj_AppTests\src\androidTest\java\org\colgram\core\ColgramUdpRelayDeviceTest.java'
L = []
A = L.append
A('package org.colgram.core;')
A('')
A('import static org.junit.Assert.assertTrue;')
A('')
A('import android.util.Log;')
A('')
A('import androidx.test.ext.junit.runners.AndroidJUnit4;')
A('')
A('import org.junit.Test;')
A('import org.junit.runner.RunWith;')
A('')
A('import java.io.DataInputStream;')
A('import java.io.OutputStream;')
A('import java.net.DatagramSocket;')
A('import java.net.InetSocketAddress;')
A('import java.net.Socket;')
A('import java.util.LinkedHashSet;')
A('import java.util.Set;')
A('')
A('/**')
A(' * Can any proxy in the pool carry the tunnel UDP?')
A(' *')
A(' * <p>This is the last route to the MASQUE edge on a network that drops UDP to it. The edge is')
A(' * silent on every registered port, while a pool of public proxies completes real MTProto')
A(' * handshakes over TCP, so if one of them also relays a UDP ASSOCIATE the tunnel has a path: the')
A(' * datagrams leave from the proxy egress rather than from this network.')
A(' *')
A(' * <p>Nothing is asserted about the count. A pool with no such node is a fact about the pool, and')
A(' * the number is printed either way because that is what tells a later run whether the route is')
A(' * worth wiring to the settings screen.')
A(' */')
A('@RunWith(AndroidJUnit4.class)')
A('public final class ColgramUdpRelayDeviceTest {')
A('')
A('    private static final String TAG = "ColgramUdpRelayTest";')
A('    private static final int TIMEOUT_MS = 6000;')
A('')
A('    @Test')
A('    public void findAProxyThatRelaysUdp() throws Exception {')
A('        Set<String> nodes = new LinkedHashSet<>();')
A('        java.lang.reflect.Field f = ColgramProxyManager.class.getDeclaredField("verifiedPool");')
A('        f.setAccessible(true);')
A('        for (Object item : (java.util.List<?>) f.get(null)) {')
A('            try {')
A('                String host = str(item, "address");')
A('                int port = num(item, "port");')
A('                int type = num(item, "type");')
A('                // type 0 is SOCKS5. Type 1 is MTProto and type 2 is a WEB bridge, and neither')
A('                // speaks SOCKS5 on the same port: asking one produces EOF, not an answer.')
A('                if (type != 0) continue;')
A('                nodes.add(host + ":" + port);')
A('            } catch (Throwable ignored) {')
A('                // A node whose fields moved is one this cannot test, not a failure.')
A('            }')
A('        }')
A('        Log.i(TAG, "SOCKS5 candidates in the pool: " + nodes.size() + " " + nodes);')
A('        int relayed = 0;')
A('        for (String node : nodes) {')
A('            if (associate(node)) {')
A('                relayed++;')
A('                Log.i(TAG, "RELAYS UDP: " + node);')
A('            }')
A('        }')
A('        Log.i(TAG, "nodes that relay UDP: " + relayed + " of " + nodes.size());')
A('        assertTrue("relay probe ran", relayed >= 0 && nodes.size() >= 0);')
A('    }')
A('')
A('    private static String str(Object item, String field) throws Exception {')
A('        java.lang.reflect.Field x = item.getClass().getDeclaredField(field);')
A('        x.setAccessible(true);')
A('        return String.valueOf(x.get(item));')
A('    }')
A('')
A('    private static int num(Object item, String field) throws Exception {')
A('        java.lang.reflect.Field x = item.getClass().getDeclaredField(field);')
A('        x.setAccessible(true);')
A('        return (Integer) x.get(item);')
A('    }')
A('')
A('    /** True when this proxy completes a UDP ASSOCIATE and names an address we can be reached on. */')
A('    private static boolean associate(String node) {')
A('        Socket ctrl = null;')
A('        try {')
A('            int colon = node.lastIndexOf(":");')
A('            String host = node.substring(0, colon);')
A('            int port = Integer.parseInt(node.substring(colon + 1));')
A('            java.net.InetAddress[] a = ColgramDohResolver.resolveOrSystem(host);')
A('            if (a == null || a.length == 0) {')
A('                Log.i(TAG, node + ": no address over DoH");')
A('                return false;')
A('            }')
A('            ctrl = new Socket();')
A('            ctrl.connect(new InetSocketAddress(a[0], port), TIMEOUT_MS);')
A('            ctrl.setSoTimeout(TIMEOUT_MS);')
A('            DataInputStream in = new DataInputStream(ctrl.getInputStream());')
A('            OutputStream out = ctrl.getOutputStream();')
A('')
A('            out.write(new byte[]{0x05, 0x01, 0x00});')
A('            out.flush();')
A('            if (in.read() != 0x05 || in.read() != 0x00) {')
A('                Log.i(TAG, node + ": not a SOCKS proxy");')
A('                return false;')
A('            }')
A('')
A('            DatagramSocket dgram = new DatagramSocket();')
A('            byte[] mine = dgram.getLocalAddress().getAddress();')
A('            out.write(new byte[]{0x05, 0x03, 0x00, 0x01,')
A('                    mine[0], mine[1], mine[2], mine[3],')
A('                    (byte) (dgram.getLocalPort() >> 8), (byte) dgram.getLocalPort()});')
A('            out.flush();')
A('            dgram.close();')
A('')
A('            int rv = in.read();')
A('            int rc = in.read();')
A('            if (rv != 0x05 || rc != 0x00) {')
A('                Log.i(TAG, node + ": associate refused, code " + rc);')
A('                return false;')
A('            }')
A('            in.read(); // RSV')
A('            int atyp = in.read();')
A('            if (atyp == 0x01) {')
A('                byte[] q = new byte[4];')
A('                in.readFully(q);')
A('            } else if (atyp == 0x03) {')
A('                int len = in.read();')
A('                byte[] q = new byte[Math.max(0, len)];')
A('                if (len > 0) in.readFully(q);')
A('            } else if (atyp == 0x04) {')
A('                byte[] q = new byte[16];')
A('                in.readFully(q);')
A('            }')
A('            int bPort = (in.read() << 8) | in.read();')
A('            Log.i(TAG, node + ": associate ok, bound port " + bPort);')
A('            return bPort != 0;')
A('        } catch (Throwable t) {')
A('            Log.i(TAG, node + ": " + t.getClass().getSimpleName());')
A('            return false;')
A('        } finally {')
A('            try {')
A('                if (ctrl != null) ctrl.close();')
A('            } catch (Throwable ignored) {')
A('            }')
A('        }')
A('    }')
A('}')
src = chr(10).join(L) + chr(10)
open(dst, 'w', encoding='utf-8').write(src)
print('written', len(src))