import os
dst = r'C:\Colgram\Telegram-Src\TMessagesProj_AppTests\src\androidTest\java\org\colgram\core\ColgramPoolShapeDeviceTest.java'
L=[]; A=L.append
A('package org.colgram.core;')
A('')
A('import static org.junit.Assert.assertTrue;')
A('')
A('import android.util.Log;')
A('')
A('import androidx.test.ext.junit.runners.AndroidJUnit4;')
A('')
A('import org.junit.Test;')
A('import org.junit.runner.RunWith;')
A('')
A('import java.util.List;')
A('')
A('/**')
A(' * What is actually in the proxy pool, by transport.')
A(' *')
A(' * <p>The SOCKS5 feeds are fetched successfully - 69KB and 723KB of them - and every one reports')
A(' * "added 0". This says whether the pool is full, whether the transport slots are occupied by the')
A(' * other type, and how many entries carry a verdict, because those three decide whether the harvest')
A(' * is failing or is simply being refused entry.')
A(' */')
A('@RunWith(AndroidJUnit4.class)')
A('public final class ColgramPoolShapeDeviceTest {')
A('')
A('    private static final String TAG = "ColgramPoolShape";')
A('')
A('    @Test')
A('    public void reportThePoolByTransport() throws Exception {')
A('        java.lang.reflect.Field f = ColgramProxyManager.class.getDeclaredField("verifiedPool");')
A('        f.setAccessible(true);')
A('        List<?> pool = (List<?>) f.get(null);')
A('        int socks = 0, mtproto = 0, web = 0, dpi = 0;')
A('        int withVerdict = 0, withoutVerdict = 0;')
A('        for (Object item : pool) {')
A('            int type = num(item, "type");')
A('            if (type == 0) socks++; else if (type == 1) mtproto++; else web++;')
A('            int failures = num(item, "failedVerdicts");')
A('            if (failures > 0) withVerdict++; else withoutVerdict++;')
A('        }')
A('        Log.i(TAG, "pool size=" + pool.size() + " socks=" + socks + " mtproto=" + mtproto')
A('                + " web=" + web + " failedVerdicts>0=" + withVerdict + " none=" + withoutVerdict);')
A('        Log.i(TAG, "MAX_SOCKS_CANDIDATES and MAX_POOL_SIZE are the caps a full pool hits");')
A('        assertTrue("pool readable", pool.size() >= 0);')
A('    }')
A('')
A('    private static int num(Object item, String field) throws Exception {')
A('        java.lang.reflect.Field x = item.getClass().getDeclaredField(field);')
A('        x.setAccessible(true);')
A('        return (Integer) x.get(item);')
A('    }')
A('}')
open(dst,'w',encoding='utf-8').write(chr(10).join(L)+chr(10))
print('written')