package org.colgram.core;

import android.content.Context;
import android.util.Log;

import androidx.test.ext.junit.runners.AndroidJUnit4;
import androidx.test.platform.app.InstrumentationRegistry;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.ByteArrayOutputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.util.Base64;

/**
 * Does the engine complete a WireGuard handshake with no tunnel at all?
 *
 * <p>Everything measured so far about the empty handshake has come through the full tunnel: a TUN
 * inbound, a VPN consent dialog, Android's routing table, and a route rule sending everything to the
 * endpoint. On the device the engine dials the right address from the right interface and writes a
 * WireGuard message-type byte followed by 1199 zeros - no sender static, no ephemeral, no mac - and
 * that is true whether or not traffic is flowing.
 *
 * <p>So the tunnel is removed from the question. This profile has one endpoint and one local
 * listener and no TUN, no consent, no Android routes: the engine has nothing to do but form a
 * handshake and send it. If it sends a complete one here, the tunnel was the cause and it is a
 * wiring problem. If it sends the same empty type byte, the endpoint configuration is the cause and
 * no amount of routing will fix it.
 *
 * <p>Either way the relay answers, and the relay is a real WireGuard peer: it either completes a
 * session or it does not. The app cannot see that, so it is stated here as a measurement to be read
 * in the relay log rather than asserted from this side.
 */
@RunWith(AndroidJUnit4.class)
public final class ColgramDeviceEndpointOnlyTest {

    private static final String TAG = "ColgramEndpointOnly";
    private static final String RELAY_HOST = "10.0.2.2";
    private static final int RELAY_PORT = 51823;
    private static final long WINDOW_MS = 40_000L;

    /**
     * A keypair generated by hand, not the one WARP's registration returned.
     *
     * <p>Everything measured so far runs on a single private key, and a device that cannot derive a
     * public key from its own private key produces exactly what was seen on the wire: an initiation
     * of the correct length - 148 bytes - containing a message-type byte and nothing else. The WARP
     * key is valid on paper, since a public key was derived from it by hand and came out well formed,
     * but paper is not the engine's parser, and every other variable has been ruled out except this
     * one.
     *
     * <p>Fixed rather than random, so it is a constant anyone can re-derive instead of a value whose
     * provenance is a detail in a log. Generated by scripts/make-test-keypair.py, which shows the
     * arithmetic. The relay keeps its own key: it accepts any public key and refuses the handshake
     * later, which is not what this measures.
     */
    private static final String OWN_PRIVATE_KEY = "AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHl8=";

    @Test
    public void theEngineHandshakesWithNoTunnelInvolved() throws Exception {
        Context context = InstrumentationRegistry.getInstrumentation().getTargetContext();

        // Register if this package has not already done so. Every instrumentation run installs a
        // fresh copy, so the WARP identity the registration produced is gone every time - and this
        // test needs a private key to build a profile at all. The relay test does the same; doing it
        // here too is what keeps the two comparable, which is the whole point of this profile.
        Class<?> warp = Class.forName("org.colgram.core.ColgramWarp");
        if (!Boolean.TRUE.equals(warp.getMethod("isRegistered").invoke(null))) {
            Log.i(TAG, "no WARP registration in this package; registering one");
            warp.getMethod("register", Context.class).invoke(null, context);
        }

        String relayKey = readRelayKey(context);
        if (relayKey == null) {
            Log.w(TAG, "no relay public key on the device, so there is nothing to handshake with");
            return;
        }

        String profile = endpointOnlyProfile(context, relayKey);
        Log.i(TAG, "profile: " + profile);

        // The other shape, checked first and deliberately allowed to fail: the engine names a field
        // it does not know, and that message is the only authority on which of the two forms it
        // decodes. Logged rather than asserted, because a rejection here is the useful result.
        String alternative = outboundPeerProfile(context, relayKey);
        Log.i(TAG, "alternative profile: " + alternative);
        try {
            Class.forName("io.nekohasekai.libbox.Libbox")
                    .getMethod("checkConfig", String.class).invoke(null, alternative);
            Log.i(TAG, "the engine ACCEPTS the outbound-peer shape");
        } catch (Exception rejected) {
            Throwable cause = rejected.getCause() == null ? rejected : rejected.getCause();
            Log.i(TAG, "the engine REJECTS the outbound-peer shape: " + cause);
        }

        setupEngine(context);
        startEngine(context, profile);
        Log.i(TAG, "the endpoint is running with no TUN, no consent and no Android routes");

        // Traffic is what makes a lazy endpoint initiate, and the request has to reach the ENGINE's
        // own listener for the endpoint to have a packet to carry. A plain socket to 127.0.0.1:2080
        // is the shortest path: the engine owns that listener, the route rule sends everything to
        // the endpoint, and nothing here depends on Android's routing table at all.
        long expires = android.os.SystemClock.elapsedRealtime() + WINDOW_MS;
        int attempts = 0;
        while (android.os.SystemClock.elapsedRealtime() < expires) {
            driveThroughLocalListener();
            attempts++;
            Thread.sleep(1500L);
        }
        Log.i(TAG, "drove " + attempts + " requests through the local listener for "
                + (WINDOW_MS / 1000L) + "s. Whether a handshake completed is visible in the"
                + " relay log and nowhere else.");
    }

    /** A profile with one endpoint and one loopback listener. No tun inbound, no routing. */
    private static String endpointOnlyProfile(Context context, String relayKey) throws Exception {
        // A key generated here, not the one WARP's registration returned. Everything measured so
        // far runs on that one key, and a device that cannot derive a public key from its own private
        // key produces exactly what was seen: an initiation of the right length and no content. The
        // key is valid on paper - a public key was derived from it by hand - but paper is not the
        // engine's parser, and every other variable has been eliminated except this one.
        //
        // Fixed, so it is a constant anyone can re-derive rather than a random number whose
        // provenance is a detail in a log. The relay's key is left alone: the peer accepts any public
        // key and refuses the handshake later, which is not what is being measured here.
        String privateKey = privateKeyOf(context);
        if (privateKey == null) {
            throw new IllegalStateException("no WARP private key on the device");
        }
        String addresses = interfaceAddresses(context);
        // interfaceAddresses() returns a comma-separated pair; the profile wants a list. Passing the
        // whole string is accepted by the decoder and then produces one malformed address, which is
        // the sort of thing that fails deep inside a handshake rather than at load time.
        JSONArray localAddresses = new JSONArray();
        for (String address : addresses.split(",")) {
            if (address.trim().isEmpty()) {
                continue;
            }
            localAddresses.put(address.trim()
                    + (address.indexOf(':') >= 0 ? "/128" : "/32"));
        }

        JSONObject peer = new JSONObject()
                .put("address", RELAY_HOST)
                .put("port", RELAY_PORT)
                .put("public_key", relayKey)
                .put("allowed_ips", new JSONArray().put("0.0.0.0/0").put("::/0"))
                .put("reserved", new JSONArray().put(1).put(2).put(3));

        JSONObject endpoint = new JSONObject()
                .put("type", "wireguard")
                .put("tag", "warp")
                .put("address", localAddresses)
                .put("private_key", OWN_PRIVATE_KEY)
                .put("peers", new JSONArray().put(peer))
                .put("mtu", 1280);

        return new JSONObject()
                .put("log", new JSONObject().put("level", "debug").put("timestamp", true))
                .put("inbounds", new JSONArray().put(new JSONObject()
                        .put("type", "mixed")
                        .put("tag", "local")
                        .put("listen", "127.0.0.1")
                        .put("listen_port", 2080)))
                .put("outbounds", new JSONArray().put(new JSONObject()
                        .put("type", "direct")
                        .put("tag", "direct")))
                .put("route", new JSONObject().put("rules", new JSONArray().put(new JSONObject()
                        .put("ip_cidr", new JSONArray().put("0.0.0.0/0").put("::/0"))
                        .put("action", "route")
                        .put("outbound", "warp"))))
                .put("endpoints", new JSONArray().put(endpoint))
                .toString();
    }

    /**
     * The same configuration with the peer on a wireguard outbound instead of on the endpoint.
     *
     * <p>Two shapes exist for the same thing. The endpoint form - key and peers together - is what
     * the profile has always carried, and this engine accepts it: the config loaded, the tunnel came
     * up, and no field was rejected. But it then wrote 148 bytes to the relay, which is a WireGuard
     * initiation's exact length, containing a message-type byte and 147 zeros. An endpoint with a peer
     * has everything a handshake needs and would send one; an endpoint without a peer has nowhere to
     * send it and writes the header into an empty buffer. So the shape is the next thing to try, and
     * the engine will say which fields of it it knows - by name, as it did for mac1.
     *
     * <p>Written to a file rather than started, because a rejected config is the useful result here
     * and an exception would end the test before the message was read.
     */
    private static String outboundPeerProfile(Context context, String relayKey) throws Exception {
        String privateKey = privateKeyOf(context);
        String addresses = interfaceAddresses(context);
        JSONArray localAddresses = new JSONArray();
        for (String address : addresses.split(",")) {
            if (!address.trim().isEmpty()) {
                localAddresses.put(address.trim()
                        + (address.indexOf(':') >= 0 ? "/128" : "/32"));
            }
        }

        JSONObject peer = new JSONObject()
                .put("address", RELAY_HOST)
                .put("port", RELAY_PORT)
                .put("public_key", relayKey)
                .put("allowed_ips", new JSONArray().put("0.0.0.0/0").put("::/0"))
                .put("reserved", new JSONArray().put(1).put(2).put(3));

        return new JSONObject()
                .put("log", new JSONObject().put("level", "debug").put("timestamp", true))
                .put("inbounds", new JSONArray().put(new JSONObject()
                        .put("type", "mixed")
                        .put("tag", "local")
                        .put("listen", "127.0.0.1")
                        .put("listen_port", 2080)))
                .put("outbounds", new JSONArray()
                        .put(new JSONObject()
                                .put("type", "wireguard")
                                .put("tag", "warp")
                                .put("peers", new JSONArray().put(peer)))
                        .put(new JSONObject()
                                .put("type", "direct")
                                .put("tag", "direct")))
                .put("route", new JSONObject().put("rules", new JSONArray().put(new JSONObject()
                        .put("ip_cidr", new JSONArray().put("0.0.0.0/0").put("::/0"))
                        .put("action", "route")
                        .put("outbound", "warp"))))
                .put("endpoints", new JSONArray().put(new JSONObject()
                        .put("type", "wireguard")
                        .put("tag", "wg-key")
                        .put("address", localAddresses)
                        .put("private_key", privateKey)
                        .put("mtu", 1280)))
                .toString();
    }

    /** One request to the engine's own listener, so the endpoint has a packet to carry. */
    private static void driveThroughLocalListener() {
        java.net.Socket socket = null;
        try {
            socket = new java.net.Socket();
            socket.connect(new java.net.InetSocketAddress("127.0.0.1", 2080), 800);
            socket.setSoTimeout(800);
            socket.getOutputStream().write(
                    "GET / HTTP/1.1\r\nHost: 1.1.1.1\r\nConnection: close\r\n\r\n"
                            .getBytes("UTF-8"));
            socket.getOutputStream().flush();
            // The read is what makes this a measurement. If the listener answers, a request reached
            // it, and with the route rule sending everything to the endpoint, the endpoint was handed
            // that packet. Nothing answering means the request died before the engine saw it, which
            // is a different fault from an endpoint that was handed traffic and stayed silent.
            int answered = socket.getInputStream().read(new byte[64]);
            Log.i(TAG, "the listener answered with " + answered + " byte(s)");
        } catch (Throwable ignored) {
            // The listener may answer with a reset, and that is fine - the request was made.
            Log.i(TAG, "the listener did not answer: " + ignored);
        } finally {
            if (socket != null) {
                try {
                    socket.close();
                } catch (Throwable ignored) {
                    // Closing is best effort; nothing depends on the outcome.
                }
            }
        }
    }

    private static String readRelayKey(Context context) {
        for (File candidate : new File[]{
                new File("/data/local/tmp/colgram-relay-key.txt"),
                new File(context.getCacheDir(), "colgram-relay-key.txt")}) {
            if (!candidate.exists()) {
                continue;
            }
            try (DataInputStream in = new DataInputStream(new FileInputStream(candidate))) {
                ByteArrayOutputStream buffer = new ByteArrayOutputStream();
                byte[] chunk = new byte[256];
                int read;
                while ((read = in.read(chunk)) > 0) {
                    buffer.write(chunk, 0, read);
                }
                for (String line : buffer.toString("UTF-8").split("\\r?\\n")) {
                    String trimmed = line.trim();
                    if (trimmed.startsWith("PEER_PUBLIC_KEY")) {
                        return trimmed.substring("PEER_PUBLIC_KEY".length()).trim();
                    }
                }
            } catch (Exception unreadable) {
                Log.w(TAG, "cannot read " + candidate + ": " + unreadable);
            }
        }
        return null;
    }

    private static String callStatic(Class<?> type, String name, Class<?>[] signature, Object... args)
            throws Exception {
        java.lang.reflect.Method method = type.getDeclaredMethod(name, signature);
        method.setAccessible(true);
        return (String) method.invoke(null, args);
    }

    private static String privateKeyOf(Context context) throws Exception {
        return callStatic(Class.forName("org.colgram.core.ColgramWarp"), "getPrivateKey",
                new Class<?>[0]);
    }

    private static String interfaceAddresses(Context context) throws Exception {
        return callStatic(Class.forName("org.colgram.core.ColgramWarp"), "interfaceAddresses",
                new Class<?>[0]);
    }

    private static void setupEngine(Context context) throws Exception {
        File base = new File(context.getCacheDir(), "libbox-endpoint-only");
        //noinspection ResultOfMethodCallIgnored
        base.mkdirs();
        File temp = new File(base, "tmp");
        //noinspection ResultOfMethodCallIgnored
        temp.mkdirs();
        Class<?> options = Class.forName("io.nekohasekai.libbox.SetupOptions");
        Object setup = options.getConstructor().newInstance();
        options.getMethod("setBasePath", String.class).invoke(setup, base.getAbsolutePath());
        options.getMethod("setWorkingPath", String.class)
                .invoke(setup, new File(base, "work").getAbsolutePath());
        options.getMethod("setTempPath", String.class).invoke(setup, temp.getAbsolutePath());
        options.getMethod("setCrashReportSource", String.class).invoke(setup, "colgram");
        options.getMethod("setDebug", boolean.class).invoke(setup, true);
        Class.forName("io.nekohasekai.libbox.Libbox")
                .getMethod("setup", options).invoke(null, setup);
    }

    private static void startEngine(Context context, String profile) throws Exception {
        Class<?> handlerType = Class.forName("io.nekohasekai.libbox.CommandServerHandler");
        Object handler = java.lang.reflect.Proxy.newProxyInstance(
                handlerType.getClassLoader(), new Class<?>[]{handlerType},
                (proxy, method, args) -> {
                    Class<?> returnType = method.getReturnType();
                    if (returnType == int.class) return 0;
                    if (returnType == boolean.class) return false;
                    return null;
                });
        Class<?> platformType = Class.forName("io.nekohasekai.libbox.PlatformInterface");
        Object platform = java.lang.reflect.Proxy.newProxyInstance(
                platformType.getClassLoader(), new Class<?>[]{platformType},
                (proxy, method, args) -> {
                    Class<?> returnType = method.getReturnType();
                    if (returnType == int.class) return 0;
                    if (returnType == boolean.class) return false;
                    if (returnType == String.class) return "";
                    return null;
                });
        Class<?> serverType = Class.forName("io.nekohasekai.libbox.CommandServer");
        Object server = serverType
                .getConstructor(handlerType, platformType)
                .newInstance(handler, platform);
        serverType.getMethod("start").invoke(server);
        serverType.getMethod("startOrReloadService", String.class,
                        Class.forName("io.nekohasekai.libbox.OverrideOptions"))
                .invoke(server, profile,
                        Class.forName("io.nekohasekai.libbox.OverrideOptions")
                                .getConstructor().newInstance());
    }
}
